services:
  profile-service:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - profile-service-db
    networks:
      - user_profile_net
      - app-network
#    env_file:
#      - .env
    environment:
      - DB_HOST=profile-service-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
  profile-service-db:
    image: postgres:15
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - user_profile_net
volumes:
  pgdata:

networks:
  user_profile_net:
      driver: bridge
  app-network:
      external: true